# Generated by Django 2.2.13 on 2020-07-19 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('clubKey', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Club Key')),
                ('zone', models.IntegerField(verbose_name='Zone')),
                ('clubCode', models.IntegerField(verbose_name='Club Code')),
                ('logo', models.ImageField(upload_to='', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Club Profile',
                'verbose_name_plural': 'Club Profiles',
            },
        ),
    ]
