# Generated by Django 2.2.13 on 2020-07-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0006_auto_20200719_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(default='district_logo.png', upload_to='media/logos', verbose_name='Logo'),
        ),
    ]
