# Generated by Django 2.2.13 on 2020-07-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportId',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Report Id'),
        ),
    ]
