# Generated by Django 2.2.13 on 2020-07-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0002_auto_20200719_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='month',
            field=models.DateTimeField(verbose_name='Month'),
        ),
    ]
