# Generated by Django 2.2.13 on 2020-07-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0003_auto_20200719_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reportId',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Report Id'),
        ),
    ]
