# Generated by Django 2.2.13 on 2020-07-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0004_auto_20200719_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dues01',
        ),
        migrations.RemoveField(
            model_name='report',
            name='dues02',
        ),
        migrations.RemoveField(
            model_name='report',
            name='dues03',
        ),
        migrations.AddField(
            model_name='report',
            name='dues04',
            field=models.CharField(default='NA', max_length=10, verbose_name='District Dues paid in this month'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='dues00',
            field=models.CharField(default='', max_length=10, verbose_name='Dues paid upto last month'),
        ),
        migrations.AlterField(
            model_name='report',
            name='suggestion00',
            field=models.TextField(default='', max_length=99, verbose_name='Suggestions'),
        ),
    ]
