# Generated by Django 2.2.13 on 2020-07-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0009_auto_20200721_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bod',
            name='bod0',
            field=models.CharField(default='', max_length=5, verbose_name='Meeting Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gbm',
            name='gbm0',
            field=models.CharField(default='', max_length=5, verbose_name='Meeting Number'),
            preserve_default=False,
        ),
    ]
