# Generated by Django 2.2.13 on 2020-07-21 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0010_auto_20200721_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futureevent',
            old_name='futurEvent0',
            new_name='futureEvent0',
        ),
        migrations.RenameField(
            model_name='futureevent',
            old_name='futurEvent1',
            new_name='futureEvent1',
        ),
        migrations.RenameField(
            model_name='futureevent',
            old_name='futurEvent2',
            new_name='futureEvent2',
        ),
        migrations.RenameField(
            model_name='futureevent',
            old_name='futurEvent3',
            new_name='futureEvent3',
        ),
    ]
