# Generated by Django 2.2.13 on 2020-07-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0012_auto_20200721_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bod',
            name='bod0',
            field=models.CharField(max_length=2, verbose_name='Meeting Number'),
        ),
        migrations.AlterField(
            model_name='bod',
            name='bod2',
            field=models.CharField(max_length=100, verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='bod',
            name='bod5',
            field=models.CharField(max_length=4, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event1',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event2',
            field=models.CharField(max_length=3, verbose_name='Avenue'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event3',
            field=models.CharField(max_length=5, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event4',
            field=models.CharField(max_length=5, verbose_name='Volunteer Hours'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event5',
            field=models.CharField(max_length=7, verbose_name='Funds Raised'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event6',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='futureevent',
            name='futureEvent1',
            field=models.CharField(max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='futureevent',
            name='futureEvent2',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='futureevent',
            name='futureEvent3',
            field=models.CharField(max_length=3, verbose_name='Avenue'),
        ),
        migrations.AlterField(
            model_name='gbm',
            name='gbm0',
            field=models.CharField(max_length=2, verbose_name='Meeting Number'),
        ),
        migrations.AlterField(
            model_name='gbm',
            name='gbm2',
            field=models.CharField(max_length=100, verbose_name='Agenda'),
        ),
        migrations.AlterField(
            model_name='gbm',
            name='gbm5',
            field=models.CharField(max_length=4, verbose_name='Attendance'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin00',
            field=models.CharField(max_length=15, verbose_name='Name of Bulletin'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin02',
            field=models.CharField(max_length=50, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin03',
            field=models.DateTimeField(verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin04',
            field=models.DateTimeField(verbose_name='Last Issued on'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin05',
            field=models.CharField(max_length=15, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dues00',
            field=models.CharField(default='', max_length=6, verbose_name='Dues paid upto last month'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dues04',
            field=models.CharField(max_length=6, verbose_name='District Dues paid in this month'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback00',
            field=models.BooleanField(verbose_name='Feedback Q1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback01',
            field=models.BooleanField(verbose_name='Feedback Q2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback02',
            field=models.BooleanField(verbose_name='Feedback Q3'),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedback03',
            field=models.BooleanField(verbose_name='Feedback Q4'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix00',
            field=models.CharField(max_length=4, verbose_name='Members at the beginning of the month - Male'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix01',
            field=models.CharField(max_length=4, verbose_name='Members at the beginning of the month - Female'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix02',
            field=models.CharField(max_length=4, verbose_name='Members at the beginning of the month - Others'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix10',
            field=models.CharField(max_length=4, verbose_name='Members added - Male'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix11',
            field=models.CharField(max_length=4, verbose_name='Members added - Female'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix12',
            field=models.CharField(max_length=4, verbose_name='Members added - Others'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix20',
            field=models.CharField(max_length=4, verbose_name='Members left - Male'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix21',
            field=models.CharField(max_length=4, verbose_name='Members left - Female'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix22',
            field=models.CharField(max_length=4, verbose_name='Members left - Others'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix30',
            field=models.CharField(max_length=4, verbose_name='Prospective - Male'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix31',
            field=models.CharField(max_length=4, verbose_name='Prospective - Female'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix32',
            field=models.CharField(max_length=4, verbose_name='Prospective - Others'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix40',
            field=models.CharField(max_length=4, verbose_name='Guests - Male'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix41',
            field=models.CharField(max_length=4, verbose_name='Guests - Female'),
        ),
        migrations.AlterField(
            model_name='report',
            name='memberMatrix42',
            field=models.CharField(max_length=4, verbose_name='Guests - Others'),
        ),
    ]
