# Generated by Django 2.2.13 on 2020-07-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0014_auto_20200722_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'get_latest_by': 'date', 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
