# Generated by Django 2.2.13 on 2020-07-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0015_auto_20200725_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bulletin03',
            field=models.DateTimeField(null=True, verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin04',
            field=models.DateTimeField(null=True, verbose_name='Last Issued on'),
        ),
    ]
