# Generated by Django 2.2.13 on 2020-07-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0017_auto_20200727_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bulletin03',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Issued on'),
        ),
        migrations.AlterField(
            model_name='report',
            name='bulletin04',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Last Issued on'),
        ),
    ]
