# Generated by Django 2.2.13 on 2020-08-05 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecReport', '0019_auto_20200727_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bod',
            name='bod1',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event0',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='futureevent',
            name='futureEvent0',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='gbm',
            name='gbm1',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='Reported on'),
        ),
    ]
